# Generated by Django 4.2.1 on 2023-05-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fond', '0004_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='jinalgany',
            field=models.IntegerField(default=123870),
        ),
        migrations.AddField(
            model_name='patient',
            name='moneySum',
            field=models.IntegerField(default=579000),
        ),
    ]
